### ISSUE TITLE
Adding merkle tree membership proof?

### ISSUE THREAD

**Issue by drewstone** [cargodog/one-of-many-proofs#35]
I know its a bit off-topic but I thought I'd ask. Your work looks amazing @cargodog and I'm planning to play around with some of the work you built and learn from it. I've had a hard time wrapping my head around how one would handle a merkle tree membership proof using marlin and curv25519-dalek. Any advice?

**Comment by cargodog** [comment]
Hi @drewstone,

I have actually put some thought into this myself. I think it is a natural next step towards large scale membership proofs. I am wrapping up a few other things first, but I hope to get to that in the coming months. I'd be happy to collaborate with you on the task, if you have ideas and/or bandwidth.

In case you are not familiar, Zcoin has done some work on this subject already: https://eprint.iacr.org/2020/430

There are a few trade-offs, as I see it. Namely, it makes batch verification difficult. Independent provers will not be able to construct batch-able proofs (Alice and Bob's proofs both verified in same batch) without revealing some secret information between each other. Even a single prover may struggle to construct a batch of proofs for multiple members they control. That said, the "single prover" case does allow for much larger anonymity sets in a given proof/verification time.

To your original question: I see no reason why Merlin of curve25519-dalek would pose any unique challenge to a tree based protocol. My original thought was to create a flexible "prover" that can be called hierarchically by passing the partial transcript across each branch in the tree. Unfortunately my thoughts on the subject are too premature to offer meaningful advice. Likewise, I would be interested to hear ideas you may have.

**Comment by cargodog** [comment]
Since this conversation is not related to an issue with the codebase, I will go ahead and close this issue. I am happy to continue this conversation though, either in this thread, or via email (see any of my `Cargo.toml` files).
